version: '3'

services:
  node-nginx:
    build: ./node-nginx
    container_name: node-nginx
    networks:
      - net-for-nginx-node
    ports:
      - 8080:80
    depends_on:
      - node-api
  node-api:
    build: ./node-api
    container_name: node-api
    entrypoint: wait-for node-database:3306 -t 40 -- ./start.sh
    volumes:
      - ./node-api:/home/node/app
    networks:
      - net-for-nginx-node
    depends_on:
      - node-database
  node-database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: node-database
    restart: always
    tty: true
    volumes:
      - ./node-mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=node-database
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - net-for-nginx-node

networks:
  net-for-nginx-node:
    driver: bridge
